### PR TITLE
Installation Mac tutorial (advanced)

### PR DESCRIPTION
**Pull request by ghost**
Made a tutorial for Mac. If you have questions about Macs, feel free to _ask me!_

~~(I know, you hat mac, but nearly 40% uses Mac)~~ bad percentage

### CODE REVIEW

**Comment by Alexander01998** [comment]
> (I know, you hat mac, but nearly 40% uses Mac)

Not even 10%.

users-by-os

**Comment by ghost** [comment]
Probably it changes regionally.

**Comment by Alexander01998** [comment]
> Probably it changes regionally.

That chart was global.

**Comment by ghost** [comment]
No, mine wasn't.

**Comment by Alexander01998** [comment]
> No, mine wasn't.

But mine was.

**Comment by ghost** [comment]
Yes, i know your was, but i suggested wurst to 5 computers, 2 were macs.

Also your message looks funny:

**Comment by DataPools** [comment]
You still should not be excluding macs.  Doesn't matter if the statistic is small. Helps mac users out a lot like myself.

**Pull request closed without merging**
