### PR TITLE
Add explanation of every command

### PR DESCRIPTION
**Pull request by ghost**
More or less detailed explanation of every single command possible.

### CODE REVIEW

**Comment by Alexander01998** [comment]
Looks quite impressive but I think you misunderstood my intention of the command list page.

It was intended to be a list of links that lead to the pages of the individual commands (which I haven't created yet). So users could go to the command list page, find the command they are looking for and then click on it to get more details about it.

---

I also noticed that you are using a lot of quotes. Quotes should only be used sparingly because they make the text very big. Look at the [AuthMeCracker](https://www.wurst-client.tk/wiki/Force_OP_%28AuthMeCracker%29/) page for an example.

**Comment by ghost** [comment]
Oh okay, i'll use the Code-Signs instead (`these ones`). And you want to have a different WIki Page for every Command? Then i'll work on that ^^

**Comment by Alexander01998** [comment]
> And you want to have a different WIki Page for every Command?

Yes, exactly.

> Oh okay, i'll use the Code-Signs instead (these ones)

As a best practise,
- use `code` for commands ("Type `.nuker mode <mode>` to change the Nuker mode."),
- `<kbd>` for buttons ("Click the <kbd>Back</kbd> button once it's done.")
- and plain text for descriptions ("Flight allows you to fly around.").

**Comment by ghost** [comment]
Changed and a Pull request was created.

**Pull request closed without merging**
