### PR TITLE
Markdown Wiki Page for every Command

### PR DESCRIPTION
**Pull request by ghost**
Created a seperate file for every Command. Markdown should be as mentioned in the previous Pull Request. index.md still needs to be updated with the links to the specific Commands, but I had no exact Idea how to do so. So I'll change it later on. :checkered_flag:

### CODE REVIEW

**Comment by Alexander01998** [comment]
Cleaned up & merged about half of the pages. The rest was just too much for me.

If you want to clean up the remaining pages yourself, feel free to open another PR.

**Comment by ghost** [comment]
Oh, okay. Thanks for the feedback, i'll work on it.. tomorrow. I just am done for today.

**Comment by Alexander01998** [comment]
> I just am done for today.

Yeah, me too. Just counted the pages, they are 22 already.

**Comment by ghost** [comment]
Oh, can I add you on Skype or something similar, so communication goes a bit quicker? And then I can let you check some stuff before I push it.

**Comment by Alexander01998** [comment]
OK.

**Pull request merged**
