### PR TITLE
Added 5 new mods

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Alexander01998** [comment]
Going to merge that once Wurst 2.1 is released.

**Comment by OMGchangeMYusername** [comment]
wot is tired :o?

**Comment by Alexander01998** [comment]
> wot is tired :o?

https://twitter.com/Wurst_Imperium/status/620161578390945792

**Comment by ghost** [comment]
@Alexander01998  hey you forgot this!

**Pull request merged**
